package io.lemonjuice.flan_mai_plugin.refence;

public class Credits {
    public static final String LINE1 = "Designed by Yuri-YuzuChaN & BlueDeer233. | Java ver. transformed by LemonJuice95";
    public static final String LINE2 = "Generated by " + ConfigRefs.BOT_NAME.get() + ".";
}
